### ISSUE TITLE
Welcome to HakinCodes Contributor's Hack 2020

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#1]
Hello, Everyone ✨🙌

Thanks for showing your interest in being a part of the [Contributor's Hack](https://hakincodes.tech/) 💥

We are super delighted to have you onboardd for your Contributions on [Malaria Detection](https://github.com/HakinCodes/Malaria-Detection) 🙌

Here are the Mentors for the Project: 

| Name 📛  |      Social Media #️⃣ |  Github 🐱‍💻 |
|----------|:-------------:|------:|
| Vishnu Varthan Rao |  [LinkedIn](https://www.linkedin.com/in/vishnu-varthan-rao-765345175/) | [Github](https://github.com/VarthanV) |
| Sarthak Kundra |    [LinkedIn](https://www.linkedin.com/in/sarthak-kundra-2b6247189/) |   [Github](https://github.com/sarthakkundra) |
| Balaka Biswas | [LinkedIn](https://www.linkedin.com/in/balaka-biswas/) |  [Github](https://github.com/BALaka-18) |
| Bhadresh Savani | [LinkedIn](https://www.linkedin.com/in/bhadreshsavani/) | [Github](https://github.com/bhadreshpsavani) |
| Abdul Waheed | [LinkedIn](https://www.linkedin.com/in/abdul-waheed-26b123126/) | [Github](https://github.com/macabdul9) |
| Sanjiban Sengupta | [LinkedIn](https://www.linkedin.com/in/sanjiban-sengupta/) | [Github](https://github.com/kahanikaar) |

Here are some 12 Rules, you should be following while doing Open-Source to make your Contributions shine during the whole process:
- Be Nice, Be Respectful (BNBR)
- Check if the Issue you created, exists or not.
- Make proper commit messages and document your PR well.
- Always add Comments in your Code and explain it at points.
- Being a multi-disciplinary project, people with varied specializations are expected to coordinate with each other. 
- Squash your commits before you push them.
- Always create a Pull Request from a Branch; Never from the Master.
- Follow proper Code conventions. Using i, j in Loops show a poor understanding of Code Quality. Use proper Variable, Function Names.
- Issues would be served on "First Come, First Serve" basis.
- Issues would be tagged as Beginner, Easy, Medium, Hard. Scores would be assigned on the difficulty of Issue you solve.
- Code would be reviewed by Mentors before they are merged. Every PR requires 3 Reviews.
- No person can take up more than 2 Issues at a single point of time.

<b>Regards,</b>
<i>Harsh Mishra (@harshcasper), Project Administrator</i> 🤗

**Comment by BALaka-18** [comment]
@HarshCasper I hope all mentors have been provided triage access. Kindly see to it once, because we need access in order to assign issues, labels and review code, plus take actions on them.
Thanks,
Balaka Biswas (@BALaka-18), Project Mentor.

**Comment by HarshCasper** [comment]
I have sent invites `Maintain` Invite Access to all Mentors. Kindly check that out @BALaka-18

**Comment by BALaka-18** [comment]
> I have sent invites `Maintain` Invite Access to all Mentors. Kindly check that out @BALaka-18

@HarshCasper I have accepted. Thank you.

**Comment by kahanikaar** [comment]
I was selected as a Mentor for HakinCodes and planned for contributing in Malaria Detection Project, but was not added into the Mentor's List, can it be done now? @HarshCasper @BALaka-18 , can check my Profiles here
[Linkedin](https://www.linkedin.com/feed/)
[Github](https://github.com/kahanikaar)
