### ISSUE TITLE
Create the home page for React application

### ISSUE THREAD

**Issue by sarthakkundra** [HakinCodes/Malaria-Detection#106]
## Type
New feature ( User Interface )

## Description
The React app has a pages sub-folder where all the pages will go.
Make the home page as per the approved UI.

**Note** You don't need to make the navbar as that is a separate component and that work has been assigned to someone.

## Tools
JSX
HTML
Bootstrap (react-bootstrap)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?
Yes.

**Comment by nooras** [comment]
Hey i wanted to try this... can You assign me? as i am new to React... I want to work on this... @sarthakkundra 
And 1 more where is UI?

**Comment by sarthakkundra** [comment]
@nooras You have 7 days to work on this issue. Make a folder called 'pages' inside of components and make a file called HomePage.js and work in it. The approved UI was sent to the Slack channel, it might be available somewhere in the repo also.

**Comment by nooras** [comment]
Okay sir And where I have to put html file ? @sarthakkundra

**Comment by sarthakkundra** [comment]
@nooras It's a React page so you won't need a separate HTML file. Are you sure you want to do this, this is a bit advanced work

**Comment by nooras** [comment]
Yes yess

**Comment by sarthakkundra** [comment]
@nooras All the best! :) Feel free to ask for help here if you're stuck

**Comment by nooras** [comment]
## Home page done @sarthakkundra 
![home](https://user-images.githubusercontent.com/30138146/92101793-42b5b400-edfb-11ea-8fbc-e4bcb4a18ec9.gif)

**Comment by nooras** [comment]
Do close this issue... Work is already done and merged #129 @sarthakkundra

**Comment by sarthakkundra** [comment]
@nooras this is a PR not an issue and we've merged the restyled PR so you can go ahead and delete it.

**Comment by nooras** [comment]
I mean to say this (Current issue page on which we commenting each other) #106 ..... 😅 @sarthakkundra
