### ISSUE TITLE
Jinja Templating 

### ISSUE THREAD

**Issue by sameersrivastava13** [HakinCodes/Malaria-Detection#109]
## Type

new feature / advancement in original

## Description

Ability to create reusable templates for our web application. There are lots of elements in the website that are currently common and in future will be common like the header or footer or the navigation bar. So instead of copy pasting the exact same code on every single page of the website we can simply create a common template `layout.html` which will have all the common elements and then we can inherit that `layout.html` in other pages using the template engine **jinja2** of flask. It also improves the speed and performance as it compiles template source code to Python bytecode when it's first loaded, so the template is only parsed once, resulting in better runtime performance.

## Tools

HTML
Python (flask)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by sameersrivastava13** [comment]
Please assign me this issue.

**Comment by sarthakkundra** [comment]
Sounds good. You have 5 days to make the template for the home page. Refer to the approved UI for the design and feel free to comment here or ask on Slack in case of any issues.

**Comment by sameersrivastava13** [comment]
> Sounds good. You have 5 days to make the template for the home page. Refer to the approved UI for the design and feel free to comment here or ask on Slack in case of any issues.

@sarthakkundra  Actually keep this issue on-hold. I was not talking about making the home page of our web application according to the UI approved.
i was just planning to add jinja templating in the current basic flask setup or you can just close this issue.
After our home page is ready we can open the same issue again to improve the functionality.
