### ISSUE TITLE
Updation of numpy version is required

### ISSUE THREAD

**Issue by himanshujaidka** [HakinCodes/Malaria-Detection#110]
## Type

(specify whether it is a bug / new feature / advancement in original)

## Description
Upgrade the numpy version to <=1.19.0
![Screenshot (61)](https://user-images.githubusercontent.com/58654018/91581237-d30f7700-e96b-11ea-89d1-f9a713428bc2.png)

(A clear and concise description of what the feature/Bug is.)

## Tools

(required tools / coding languages)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### Motivation

(Please outline the motivation for the proposal.)

**Comment by macabdul9** [comment]
open cmd with admin rights and then install the dependencies (--user might not work in windows)
