### ISSUE TITLE
Sigmoid not changed to Softmax in model_malaria_detection.ipynb 

### ISSUE THREAD

**Issue by kritikaparmar-programmer** [HakinCodes/Malaria-Detection#121]
## Type

Typo

## Description

After being asked to use Softmax instead of Sigmoid, I forgot to change that in the markdown cell..

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

This is the ss showing the issue..
![picmodel](https://user-images.githubusercontent.com/59971890/91935410-436f1d00-ed0b-11ea-9120-66d8bc88674d.png)

**Comment by kritikaparmar-programmer** [comment]
I want to resolve this mistake.. Sorry for the inconvenience..

**Comment by macabdul9** [comment]
I am assigning this to you @kritikaparmar-programmer
