### ISSUE TITLE
Create the Landing Page for the Website [HTML+CSS+Bootstrap+JQuery]

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#123]
## Type

Advancement 

## Description

Create the Landing Page for the Website using HTML, CSS, Bootstrap and JQuery. Refer [this](https://github.com/HakinCodes/Malaria-Detection/tree/master/design/WebUI/LandingPage) for the UI Wireframe that you would need to follow. 

You will have maximum 7 Days to work on this. You don't need to work on the integration of Dark Theme for now.

## Tools

- HTML
- CSS
- Bootstrap 
- JQuery

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by devanshiv123** [comment]
@HarshCasper I would like to work on this issue.

**Comment by nooras** [comment]
I thought this is the same task as issue no #106 have

**Comment by HarshCasper** [comment]
I am assigning it to you @devanshiv123 

@nooras The Page you developed was for the React Application.

**Comment by Adyasha8105** [comment]
@HarshCasper I want to work on this?

**Comment by HarshCasper** [comment]
@devanshiv123 Are you working on this? 

If not, I am assigning this to @Adyasha8105

**Comment by devanshiv123** [comment]
> @devanshiv123 Are you working on this?
> 
> If not, I am assigning this to @Adyasha8105

@HarshCasper No, I am facing some problems, you can assign it to someone else.

**Comment by HarshCasper** [comment]
@Adyasha8105 I am assigning this to you. Kindly confirm if you will be working on this.

**Comment by AshutoshDash1999** [comment]
Can I take up this issue? But I'm not that familiar with jquery!

**Comment by nikita-1801** [comment]
I'd like to work on this.

**Comment by HarshCasper** [comment]
@nikita-1801 Would you be able to finish it up in 3 Days?

**Comment by nikita-1801** [comment]
I'll try my best!
