### ISSUE TITLE
Create the Input Page [HTML+CSS+Bootstrap+JQuery]

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#124]
## Type

Advancement

## Description

Create the Input Page using HTML, CSS, Bootstrap and JQuery. Make sure to follow this [UI Design](https://github.com/HakinCodes/Malaria-Detection/blob/master/design/webpage_designs/input_form.png) while developing the Webpage. 

## Tools

- HTML
- CSS
- Bootstrap
- JQuery

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by AdityaAshvin** [comment]
Can i work on this @HarshCasper ?

**Comment by HarshCasper** [comment]
Assigning this to you @AdityaAshvin
