### ISSUE TITLE
Create the Results Page [HTML+CSS+Bootstrap+JQuery]

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#125]
## Type

Advancement 

## Description

Create the Results Page using HTML, CSS, Bootstrap, JQuery. Make sure to follow this [UI Design](https://github.com/HakinCodes/Malaria-Detection/blob/master/design/webpage_designs/result_page.png) while developing the Webpage.

## Tools

- HTML
- CSS
- Bootstrap
- JQuery

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by ymaheshwari1** [comment]
I am interested in this. @HarshCasper

**Comment by HarshCasper** [comment]
Assigning this to you @ymaheshwari1

**Comment by HarshCasper** [comment]
Are you working on it @ymaheshwari1 ? 

If not, I will assign this to someone else.

**Comment by ymaheshwari1** [comment]
@HarshCasper No, I am having errors while setting it up. You can assign it to someone else.

**Comment by amoghatsunil** [comment]
I would like to work on this(html,css), but I am not sure about the jquery and bootstrap part

**Comment by rutujadhanawade** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
You can see what fits you the best. I am assigning this to you @amoghatsunil

**Comment by rutujadhanawade** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
Assigned to you @rutujadhanawade 

Would you be able to make a PR for this in 3 Days?

**Comment by rutujadhanawade** [comment]
Yeah 👍 I will try @HarshCasper

**Comment by rutujadhanawade** [comment]
I have made a PR #174 to close this issue and it is merged now. 
Please close this issue.
