### ISSUE TITLE
Compose a h5 File from the Data Modelling

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#126]
## Type

Feature 

## Description

Compose an h5 File from the Data Modelling and store it in the `models/` folder.

## Tools

- Jupyter Notebook
- Python

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by bhanvimenghani** [comment]
I can make a h5 file but I cannot find the models/ folder? Are you refering to the Notebooks folder?

**Comment by macabdul9** [comment]
It'd be better if some who has built the model, write a script that takes the input image path and gives the output as class(infected or not) and confidence score(max probability in case of softmax).

**Comment by bhanvimenghani** [comment]
I have no problem with it if you want you can take up the issue @macabdul9

**Comment by namanshah01** [comment]
Hey, I worked on a similar project where I saved the models weights to an h5 file(check my [pneumonia_classifier](https://github.com/namanshah01/pneumonia_classifier) repo). Can I work on this project?

**Comment by HarshCasper** [comment]
I am assigning this to you @bhanvimenghani

**Comment by bhanvimenghani** [comment]
@macabdul9 you mean you need a **test script** along with the models weight. Right?

**Comment by macabdul9** [comment]
yes, the test/inference script should take an image and predict the class (using trained model). In case you've worked on model optimization, you can optimize your model to reduce the model size and it may reduce the inference time as well.

**Comment by HarshCasper** [comment]
Are you working on this @bhanvimenghani ?

Because of this Issue, we have not been able to move forward with any other Issue.

**Comment by bhanvimenghani** [comment]
you can unassign me

**Comment by v-sonawane** [comment]
I am willing to work on this issue.

**Comment by Shubham-1105** [comment]
I have worked on this

**Comment by HarshCasper** [comment]
I am assigning this to you @v-sonawane 

Kindly make a PR by tomorrow for this

**Comment by v-sonawane** [comment]
Alongwith the h5 files(model & model weights), the script to take image path as input and predict it with confidence score is also to be uploaded in models/ folder?

**Comment by v-sonawane** [comment]
Any mentors there to acknowledge the pull request?

**Comment by macabdul9** [comment]
hey @v-sonawane I am on it

**Comment by v-sonawane** [comment]
> Alongwith the h5 files(model & model weights), the script to take image path as input and predict it with confidence score is also to be uploaded in models/ folder?

Also could you weigh in on this as well?

**Comment by macabdul9** [comment]
> > Alongwith the h5 files(model & model weights), the script to take image path as input and predict it with confidence score is also to be uploaded in models/ folder?
> 
> Also could you weigh in on this as well?

I have requested the change for the same

**Comment by v-sonawane** [comment]
Done👍🏻
