### ISSUE TITLE
Create a Model using a Custom Convolutional Neural Network using PyTorch

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#127]
## Type

Advancement

## Description

Create a Model using a Custom Convolutional Neural Network using PyTorch. This Issue is open to <b>three people</b> who wish to try out their hands in bringing out the best architecture.
## Tools

- Python
- PyTorch
- Jupyter Notebook
- Jupyter Markdown

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by kritikaparmar-programmer** [comment]
I want to work on this issue.. Please assign me...

**Comment by macabdul9** [comment]
Sure @kritikaparmar-programmer, you can work on this. Also, save the trained model for production use, and if possible write the test script as well.
