### ISSUE TITLE
Train the Model using VGG-16

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#131]
## Type

Advancement

## Description

Create and Train a Model using VGG-16, using either Keras (Tensorflow) or PyTorch. This Issue can be assigned to two people working on either of the frameworks for Data Modelling. Create a Test Script as well, which can be used to test the Script.

## Tools

- Python
- Tensorflow
- PyTorch 
- Jupyter Notebook
- Jupyter Markdown 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by rjn01** [comment]
@HarshCasper Can I work on this issue?

**Comment by BALaka-18** [comment]
> 
> 
> @HarshCasper I want to work on this issue using Keras. Can you assign me this issue?

@rjn01 assigning you the issue for Keras based implementation.
