### ISSUE TITLE
Update the README.md file

### ISSUE THREAD

**Issue by ymaheshwari1** [HakinCodes/Malaria-Detection#132]
## Type
Advancement

## Description
To update the local installation section in the README file to add the step to create a virtual environment before running the requirements.txt file

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?
Yes

**Comment by ymaheshwari1** [comment]
I am interested in working on this.

**Comment by HarshCasper** [comment]
Assigning this to you @ymaheshwari1
