### ISSUE TITLE
Build a CNN Model using Alexnet Architecture

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#145]
## Type

Advancement

## Description

Create a new CNN Model using the Alexnet Architecture. Document the Code properly for better understanding.

## Tools

- Jupyter Notebook
- PyTorch / Keras 
- Jupyter Markdown

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by namanshah01** [comment]
May I work on this please?

**Comment by rjn01** [comment]
@HarshCasper Can I work on this issue using Keras.

**Comment by HarshCasper** [comment]
I have assigned this to you @namanshah01 

You can work on this using PyTorch @rjn01

**Comment by namanshah01** [comment]
Thank you. Is it fine if i take the same dataset form kaggle https://www.kaggle.com/iarunava/cell-images-for-detecting-malaria ? Or should i use the one in your repo

**Comment by rjn01** [comment]
@HarshCasper I have not worked with PyTorch. I only know how to work using keras.
