### ISSUE TITLE
Create Unit-Tests for the Flask Application

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#146]
## Type

Advancement

## Description

Create Unit-Tests for the Flask Application using `pytest`. Add the `conftest.py` file and test the route responds with the Tests that you will be writing. Add a Github Action as well for Unit Tests to show if the Flask Application build is passing or failing.

## Tools

- PyTest 
- Python
- Github Actions
- Flask

**Comment by sameersrivastava13** [comment]
@HarshCasper I would like to work on this issue.

**Comment by HarshCasper** [comment]
Assigned to you @sameersrivastava13
