### ISSUE TITLE
Design a Page for the Project Contributors + Mentors

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#148]
## Type

Advancement

## Description

Design a Page using a UI Prototyping Tool like Adobe XD/Figma, for the Project Contributors, Mentors and Administrators. Make sure to submit the design in Image/PDF Format along with the raw file in the appropriate `design/` directory. It should have two parts: 

- Admin and Mentors
- Contributors

You can use Dummy Data for the designing part.

## Tools

- Adobe XD/Figma

**Comment by kritikaparmar-programmer** [comment]
Can I try this issue.. @HarshCasper Though I've no experience with designing. 😅

**Comment by HarshCasper** [comment]
Yeah, sure. I am assigning this to you @kritikaparmar-programmer 

You can take a look at some tutorials for the purpose. We aren't looking at anything fancy but something that can fit well with our current design.

**Comment by kritikaparmar-programmer** [comment]
![image](https://user-images.githubusercontent.com/59971890/93521404-a5579580-f94d-11ea-8c74-59ad29c07a35.png)
Hey @HarshCasper will something like this will work
This page is for project admin and mentors
I'm new to it that's why I want some suggestion..😅

**Comment by kritikaparmar-programmer** [comment]
Hey @HarshCasper I've tried something take a look and provide some suggestions.
![demo](https://user-images.githubusercontent.com/59971890/93626270-d5ac3c00-fa00-11ea-8e50-4396812f9aa0.png)

**Comment by HarshCasper** [comment]
@kritikaparmar-programmer You can reduce the Profile Picture of my size and keep it the same as the Mentors. There is absolutely no need of keeping a picture at such a large dimension. 

Make sure that the Contributors are highlighted more as they are the one making this happen.
