### ISSUE TITLE
REST API  in Flask 

### ISSUE THREAD

**Issue by macabdul9** [HakinCodes/Malaria-Detection#166]
## Type

REST API using Flask

## Description

Build a REST API to expose the trained model, we will POST an image to /predict endpoint and we need class and confidence as response. 

## Tools
- Flask
- Keras/Tensorflow/PyTorch
- REST API
- Modeling 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?
Yes

Note: One can use the test script which can be found in models/ dir, pretrained models can be found in the same dir. 
Reference: [Flask APP for OCR](https://github.com/macabdul9/attention-ocr-app)

**Comment by sameersrivastava13** [comment]
I would like to work on this issue. 
Please assign me this issue.

**Comment by macabdul9** [comment]
Sure @sameersrivastava13, I am assigning you to work on this. If possible, test your API endpoint from the React client app. You have 5 days to create a PR but earlier the merrier.

**Comment by kritikaparmar-programmer** [comment]
Hey @macabdul9 I want to try out this issue. Please assign me..

**Comment by kritikaparmar-programmer** [comment]
And also I want some more reference material if you can provide..😅

**Comment by sameersrivastava13** [comment]
> Hey @macabdul9 I want to try out this issue. Please assign me..

yeah you can ask and take this issue as I will be not active for few days. All the best.

**Comment by macabdul9** [comment]
@kritikaparmar-programmer you can work on this, I expect a PR within the stipulated time. You should check out this repo [reddit-flair-detector](https://github.com/macabdul9/reddit-flait-detector) for client server architecture.
