### ISSUE TITLE
Create the Contributor's Page

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#168]
## Type

New Feature

## Description

Develop the Contributor's Page and make it responsive. You can refer the UI wireframe from [here](https://github.com/HakinCodes/Malaria-Detection/blob/master/design/P_C%26Mentors/malaria_pa_mentors.png) and make the page responsive. Add a Contributor Table and pull the data from a JSON File. You can use a mock JSON file for now.

<b>Please note that you need to complete this issue within 3 Days of Assignment</b>

Also create a Flask endpoint for the purpose which will show the Contributor's Page.

## Tools

- HTML/CSS
- Bootstrap 
- Flask
- JS/JQuery 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by sameersrivastava13** [comment]
@HarshCasper i would like to work on this issue.
