### ISSUE TITLE
Create a Logo for the Application

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#2]
Currently, we need a Logo for our Application which would be used on our Web Application Interface. 

<b>This Issue is open for all, and will not be assigned to anyone. People interested to work on it, can mention about their work and make a PR.</b>

Tools to be used: 

- Figma
- Adobe XD
- Adobe Photoshop 

Logo Designs must be added in an appropriate form on a `design/Logo-Design/` Directory. The basic criteria we are looking for are: 

- The logo should be optimized to a 500x500 Pixel Size.
- Transparent Background must be used. 
- Design Philosophy must be documented in the PR. 

PRs would be reviewed on a rolling basis. All PRs would be reviewed by Mentors before they are finally acknowledged and merged.

**Comment by Neel2904** [comment]
@HarshCasper I would like to work on this issue

**Comment by HarshCasper** [comment]
I have assigned you the Issue @Neel2904 

You have 7 Days to work on this 🤗💥

**Comment by amandp13** [comment]
@HarshCasper I would like to work on this issue

**Comment by HarshCasper** [comment]
Hello @amandp13 

I have assigned you this Issue. Both of your PRs would be reviewed on our part before we merge it.

**Comment by DevangSharma** [comment]
I can design a logo for this

**Comment by ashishsahu1** [comment]
@HarshCasper I had designed a logo that matches with UI which I am designing. Can you just look at it once.

**Comment by VarthanV** [comment]
Do post it here @ashishsahu1

**Comment by HarshCasper** [comment]
@ashishsahu1 Make a PR. Final Logo would be decided on votes cast
