### ISSUE TITLE
Updating requirements.txt file

### ISSUE THREAD

**Issue by sameersrivastava13** [HakinCodes/Malaria-Detection#20]
## Description

As i can see in the requirements.txt file added the python packages version specified are old.
I would like to update the requirements.txt file with the latest version number.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

yes.

**Comment by macabdul9** [comment]
I have assigned you the Issue @sameersrivastava13

**Comment by BALaka-18** [comment]
Closing this issue for now, as there are no further updates to be done currently.
