### ISSUE TITLE
Create a basic Setup

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#21]
## Type

Feature/Advancement

## Description

- [x] Create a Folder named `templates` which consists of three HTML Pages. Add mock HTML Code in them to serve them from the Flask App. 
- [x] Create a Folder named 'Static` to serve Static Content and other Assets.
- [x] Link Style and Script to the HTML Code.
 
## Tools

- HTML
- CSS
- Javascript
- Python

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

### Motivation

To set a basic boilerplate for our application before we move ahead with the Development Part.

**Comment by sameersrivastava13** [comment]
@HarshCasper i would like to work on this issue.

**Comment by BALaka-18** [comment]
> @HarshCasper i would like to work on this issue.

@sameersrivastava13 did you complete your last assigned issue ?

**Comment by sameersrivastava13** [comment]
> > @HarshCasper i would like to work on this issue.
> 
> @sameersrivastava13 did you complete your last assigned issue ?

@BALaka-18 yeah it's over. I am generating the pull request for that.

**Comment by BALaka-18** [comment]
Okay do that, then you'll be assigned this issue.

**Comment by sameersrivastava13** [comment]
> Okay do that, then you'll be assigned this issue.

Done. Now please assign me this.

**Comment by AdityaAshvin** [comment]
@HarshCasper can I work on this?

**Comment by sameersrivastava13** [comment]
> @HarshCasper can I work on this?

I already asked for it bro.

**Comment by BALaka-18** [comment]
@sameersrivastava13 assigned. You have 7 days to submit a PR.
@AdityaAshvin if Sameer needs help, we'll assign you too, you can work together. Or if he's unable to complete in the given time, we'll reconsider your request.
Ask the PA once, he is also assigning two people in some issues.

**Comment by BALaka-18** [comment]
Closing this issue as it has been resolved.
