### ISSUE TITLE
Make a Contributors Guideline

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#3]
## AIM

Create Contributors Guideline to help new Contributors get started with this Project.

## Features

- Add a ```CONTRIBUTING.md``` to allow new users to get started with knowing how to contribute.
- Add Screenshots wherever possible. 
- Add the basic information about creating Issues, Pull Requests and Branching.
- Mention tutorials related to Git and Github to help them better understand.

**Comment by Neel2904** [comment]
I would like to work on this issue.

**Comment by HarshCasper** [comment]
@Neel2904 You are already assigned you one issue. I cannot assign you this until you submit a PR for the previous Issue

**Comment by Neel2904** [comment]
Okay !!

**Comment by TechTarun** [comment]
I would like to work on this issue.

**Comment by bhadreshpsavani** [comment]
I have assigned this issue to @TechTarun

**Comment by architsharrma** [comment]
i would like to work on it

**Comment by HarshCasper** [comment]
A PR for this Issue was made by @sameersrivastava13 and merged. Closing this Issue now
