### ISSUE TITLE
Create a .gitignore File

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#31]
## Type

Advancement 

## Description

Our Repository currently lacks a proper Gitignore Setup. Add a .gitignore setup so that we don't actually push code that we don;t actually intend to in the long run.

**Comment by AdityaAshvin** [comment]
Can I do it @HarshCasper?

**Comment by bhadreshpsavani** [comment]
Sure, I am assigning this issue to you @AdityaAshvin

**Comment by BALaka-18** [comment]
Closing this issue as it has been resolved for now.
