### ISSUE TITLE
Server is not running 

### ISSUE THREAD

**Issue by carrycooldude** [HakinCodes/Malaria-Detection#34]
# Server is not opening 

## Description

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

![image](https://user-images.githubusercontent.com/41143496/90374596-5c33cd80-e091-11ea-8cb3-427759ed991d.png)

**Comment by sameersrivastava13** [comment]
@carrycooldude use the correct end point defined other wise it will definitely gonna show internal server error.

**Comment by carrycooldude** [comment]
> @carrycooldude use the correct end point defined other wise it will definitely gonna show internal server error.

Can explain what end point if you saying requirement so I done with it

**Comment by sarthakkundra** [comment]
@carrycooldude what URL (endpoint) did you enter in the above screenshot?

**Comment by carrycooldude** [comment]
> @carrycooldude what URL (endpoint) did you enter in the above screenshot?

http://127.0.0.1:5000/

**Comment by carrycooldude** [comment]
> @carrycooldude what URL (endpoint) did you enter in the above screenshot?

http://127.0.0.1:5000/

**Comment by BALaka-18** [comment]
@carrycooldude The application works fine on my local system. And I don't seem to find any errors in the code.

**Comment by VarthanV** [comment]
Did this issue got resolved?

**Comment by BALaka-18** [comment]
> Did this issue got resolved?

I don't think so.
@carrycooldude please confirm whether this issue got resolved on your system.

**Comment by VarthanV** [comment]
@BALaka-18  can u pls attach the screenshots of the  error that you getting in your terminal.

**Comment by BALaka-18** [comment]
> @BALaka-18 can u pls attach the screenshots of the error that you getting in your terminal.

@VarthanV I am not getting any errors. @carrycooldude is. This issue was raised by him, not me.

**Comment by sameersrivastava13** [comment]
> > @BALaka-18 can u pls attach the screenshots of the error that you getting in your terminal.
> 
> @VarthanV I am not getting any errors. @carrycooldude is. This issue was raised by him, not me.

@BALaka-18 @VarthanV I dont think this is an issue. Please ask @carrycooldude  to share the entire browser screen shot.
Other wise try running your flask application by typing `py hello.py runserver -d` or trying using some other port number in main : `app.run(debug=True, port=8000)` or `app.run(debug=True, port=2000) `

**Comment by BALaka-18** [comment]
> > > @BALaka-18 can u pls attach the screenshots of the error that you getting in your terminal.
> > 
> > 
> > @VarthanV I am not getting any errors. @carrycooldude is. This issue was raised by him, not me.
> 
> @BALaka-18 @VarthanV I dont think this is an issue. Please ask @carrycooldude to share the entire browser screen shot.
> Other wise try running your flask application by typing `py file_name.py runserver -d` or trying using some other port number in main : `app.run(debug=True, port=8000)` or `app.run(debug=True, port=2000) `

@carrycooldude follow this.
Closing this issue.
