### ISSUE TITLE
Add a CONTRIBUTING.md guideline

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#35]
## 📚 Documentation

Currently, the Project Codebase lacks a Contributor's Guideline which is detrimental for new contributors. We need good documentation that can actually help new contributors to understand how they can start contributing to this Project. The basic features we are currently looking for are: 

- Create a ```CONTRIBUTING.md``` to allow new users to get started with knowing how to contribute.
- Add Screenshots wherever possible. 
- Add the basic information about creating Issues, Pull Requests and Branching.
- Mention tutorials related to Git and Github to help them better understand.

This Issue would be later a part of our Wiki which we are working on right now.

**Comment by sameersrivastava13** [comment]
@HarshCasper i would like to work on this. Please assign this to me.

**Comment by BALaka-18** [comment]
> @HarshCasper i would like to work on this. Please assign this to me.

Assigned.
