### ISSUE TITLE
Add Documentation on setting Tensorflow

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#36]
## Type

Advancement

## Description

Create a Documentation File using Markdown and add it into a specific `Documentation/` directory to allow new contributors to get started with setting Tensorflow. The features to be added in the documentation includes: 

- Give a basic idea about Tensorflow.
- Give a step-wise plan of setting Tensorflow on Windows/Linux/OSX Environment. 
- Add Screenshots wherever possible. 
- Add a sample Tensorflow Code to show the Library up and running.

## Tools

- Markdown
- Python
- Pip/Conda

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

### Motivation

To contribute to the Wiki of this Project in the longer run.

**Comment by ashishsahu1** [comment]
Can I work on this. @HarshCasper

**Comment by ashishsahu1** [comment]
@HarshCasper  where should keep that documentation markdown file? I mean should I create another folder for that?

**Comment by kahanikaar** [comment]
Is this issue still open @HarshCasper ?
