### ISSUE TITLE
Add Documentation on setting Flask

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#37]
## Type

Advancement

## Description

Create a Documentation File using Markdown and add it into a specific `Documentation/` directory to allow new contributors to get started with setting Flask. The features to be added in the documentation includes: 

- Give a basic idea about Flask as a Micro Web-Framework.
- Give a step-wise plan of setting Flask on Windows/Linux/OSX Environment. 
- Add Screenshots wherever possible. 
- Add a sample Flask Code with a mock endpoint to show the Server up and running.

## Tools

- Markdown
- Python
- Pip/Conda

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

### Motivation

To contribute to the Wiki of this Project in the longer run.

**Comment by rjn01** [comment]
I would like to work on this @HarshCasper

**Comment by Shubham-1105** [comment]
I have worked in flask, so i can work on the documentation

**Comment by HarshCasper** [comment]
Assigned to you @rjn01
