### ISSUE TITLE
Create an Issue + Pull Request Template

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#4]
## AIM

Create a custom Issue and Pull Request Template.

## Features

- Make an Issue Template. Any new Contributor must be able to specify if it is a new script or enhancement to an older one. It should also be specified which language he is coding it in.

- Make a Pull Request Template. Any new Contributor must be able to specify if he has met all the requirements like Clean Code, proper README and Documentation, Screenshots (If any) attached and more.

**Comment by rutujadhanawade** [comment]
I would like to work on this issue.

**Comment by HarshCasper** [comment]
I have assigned you the Issue @rutujadhanawade

**Comment by ritiksoni00** [comment]
i did open the issue way back

**Comment by ritiksoni00** [comment]
No worries ?? misunderstanding
