### ISSUE TITLE
Add Create React App Boilerplate Code

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#47]
## Type

Advancement 

## Description

I have created a Branch named `react-tensorflowjs` where our parallel development will go on. Add the React Boilerplate Code using `create-react-app` to the branch to get started with the UI Development using React. Make sure to add a `.gitignore` to prevent pushing up your `node-modules` as well.

## Tools

- NodeJS
- NPM
- Create React App CLI

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by nooras** [comment]
hey @HarshCasper  can I do this ? will you assign me  ?

**Comment by HarshCasper** [comment]
I have assigned to you @nooras

**Comment by parikshit223933** [comment]
Hello @HarshCasper, when @nooras is done with the boilerplate code, may I get started with the UI? I am pretty good with react applications. And if yes, then what should be the content for that?

**Comment by HarshCasper** [comment]
Sure @parikshit223933 

We will create specific Issues for that

**Comment by nooras** [comment]
What name i give to create react-app ?

**Comment by HarshCasper** [comment]
Name it `malarial-detection`

**Comment by nooras** [comment]
Hey @HarshCasper I went to branch react-tensorflow and there i created app using create react-app . Now its done... Now can I do commit and push ? Or have to do something else ?
