### ISSUE TITLE
Add a CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#5]
## AIM

Create a Code of Conduct which all Project Administrators, Mentors and Participants must abide by. 

## Details 

- Mention the Standards which everyone should abide by on welcoming and inclusive language including constructive criticism.
- Add the required responsibilities for Project Maintainers. 
- Mention the Scope of this Code of Conduct.

**Comment by Neel2904** [comment]
I would like to work on this issue

**Comment by HarshCasper** [comment]
@Neel2904 You are already assigned you one issue. I cannot assign you this until you submit a PR for the previous Issue

**Comment by mohit1448** [comment]
I would like to work on this issue.

**Comment by mjay4** [comment]
Can I work on this issue?

**Comment by bhadreshpsavani** [comment]
I have assigned you the issue @mohit1448

**Comment by bhadreshpsavani** [comment]
I am closing this issue since code changes are merged
