### ISSUE TITLE
Adding a splash screen

### ISSUE THREAD

**Issue by sameersrivastava13** [HakinCodes/Malaria-Detection#53]
## Type

I would like to add a splash screen to the web application.
## Description

I know the Front end part is still left for the web app but i found this really cool GIF and wanted to use this for our
web application as a loading screen to give an end user immediate feedback that an application is starting and loading in the background.

## Tools

Javascript
CSS
HTML

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

yes

![Magnify-1s-200px](https://user-images.githubusercontent.com/56088741/90670418-c5256c00-e270-11ea-8c65-3af4c7e7a736.gif)

**Comment by sameersrivastava13** [comment]
Please assign me this issue so that i can start working on it.
also we can change the color of the magnifying glass in the GIF above.

**Comment by sarthakkundra** [comment]
Looks good, you can change the color according to the approved UI

**Comment by BALaka-18** [comment]
Closing this issue as it has been resolved for now.
