### ISSUE TITLE
Adding a 404 page.

### ISSUE THREAD

**Issue by sameersrivastava13** [HakinCodes/Malaria-Detection#56]
## Description

To add a 404 error page to keep a visitor on your site even if he/she hits a page that doesn't exist. Also to change the bad User experience to a positive one by adding some links to that 404 page so that the visitor can navigate to some other page.

## Tools

python
html 
css

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

yes

**Comment by sameersrivastava13** [comment]
@HarshCasper Please assign me this issue.

**Comment by sarthakkundra** [comment]
@sameersrivastava13  Will you just add the endpoint or make the UI as well?

**Comment by BALaka-18** [comment]
@sameersrivastava13 are you willing to do the UI as well or do we assign some other participant to coordinate with you ?

**Comment by sarthakkundra** [comment]
@sameersrivastava13  I have created a seperate issue for designing. You can take it up first if you want to do the designing too.

**Comment by sameersrivastava13** [comment]
@BALaka-18 @sarthakkundra i am willing to do both the things together. 
please assign me this issue.

This is what i have designed and implemented.

![Screenshot (40)](https://user-images.githubusercontent.com/56088741/90756428-fdbd5800-e2f9-11ea-81aa-1ec57e025fb4.png)

**Comment by sameersrivastava13** [comment]
> @sameersrivastava13 are you willing to do the UI as well or do we assign some other participant to coordinate with you ?

if the design of the page is okay. Then please assign me this issue so that i can work on the backend so that whenever an incorrect end point is entered by user this 404 page should come up.

**Comment by BALaka-18** [comment]
@sarthakkundra @sameersrivastava13 let's not make separate issues for frontend and backend, it will become more clumsy and clattered. One issue will be enough to handle the building of the 404 error page. And since Sameer is willing to do both, I'm assigning it to him.
Cool ?

**Comment by sameersrivastava13** [comment]
> @sarthakkundra @sameersrivastava13 let's not make separate issues for frontend and backend, it will become more clumsy and clattered. One issue will be enough to handle the building of the 404 error page. And since Sameer is willing to do both, I'm assigning it to him.
> Cool ?

Exactly.. Please assign this to me.. and close the other issue created.
if you want any change in the design of the page then let me know i will change that immediately.

**Comment by BALaka-18** [comment]
Okay. Assigning.
@sameersrivastava13 you can check out this 404 error page that I had made for one of my projects.

![Screenshot (325)](https://user-images.githubusercontent.com/49288068/90757956-e5e6d380-e2fb-11ea-907c-20fad7a7c675.png)

**Comment by sarthakkundra** [comment]
@BALaka-18  @sameersrivastava13  I've closed the other issue so you can do both the tasks in this issue only. But for the design I'd suggest you to refer to #6 So that you use the same colors as the overall UI for uniformity. Also please get the design approved here before starting to work on it. Thanks!

**Comment by BALaka-18** [comment]
> @BALaka-18 @sameersrivastava13 I've closed the other issue so you can do both the tasks in this issue only. But for the design I'd suggest you to refer to #6 So that you use the same colors as the overall UI for uniformity. Also please get the design approved here before starting to work on it. Thanks!

Yes sure, @sameersrivastava13 please refer to #6

**Comment by sameersrivastava13** [comment]
I was planning to add the one above which i have shown or this which i have attached below:

![bandicam-2020-08-20-15-58-09-773](https://user-images.githubusercontent.com/56088741/90759998-db7a0900-e2fe-11ea-814e-a143efb8460c.gif)

**Comment by sarthakkundra** [comment]
@sameersrivastava13 These designs do not match the color scheme of the website. If you need the designs for the homepage and the input form you can message me on Slack. They will definitely help you.

**Comment by BALaka-18** [comment]
> I was planning to add the one above which i have shown or this which i have attached below:
> 
> ![bandicam-2020-08-20-15-58-09-773](https://user-images.githubusercontent.com/56088741/90759998-db7a0900-e2fe-11ea-814e-a143efb8460c.gif)

Actually, what @sarthakkundra meant was that, if you've seen the UI design already merged, the color scheme is majorly based on blue, purple and white. So your error page should be similar for a better view.

**Comment by sameersrivastava13** [comment]
@BALaka-18 @sarthakkundra 
is this okay? the color combination.

![Capture](https://user-images.githubusercontent.com/56088741/90859047-0c147e00-e3a5-11ea-82c6-cd102e5c942d.PNG)

**Comment by BALaka-18** [comment]
@sameersrivastava13 Looks better. You can increase the font size of the 2nd line and make the 'GO BACK HOME' bolder.
Let's wait for @sarthakkundra's reviews.

**Comment by sarthakkundra** [comment]
looks good to me 👍

**Comment by BALaka-18** [comment]
@sameersrivastava13 make the changes I proposed and open a PR.

**Comment by sarthakkundra** [comment]
@sameersrivastava13 see if you can add a mosquito GIF like the bee that'd look good but it's fine if you can't find it :)

**Comment by sameersrivastava13** [comment]
> @sameersrivastava13 see if you can add a mosquito GIF like the bee that'd look good but it's fine if you can't find it :)

Definitely. I'll try adding something related to that.

**Comment by sameersrivastava13** [comment]
> @sameersrivastava13 Looks better. You can increase the font size of the 2nd line and make the 'GO BACK HOME' bolder.
> Let's wait for @sarthakkundra's reviews.

Sure @BALaka-18
