### ISSUE TITLE
Designing a 404 page

### ISSUE THREAD

**Issue by sarthakkundra** [HakinCodes/Malaria-Detection#59]
## Type
User Interface
New Feature

## Description
The website most definitely needs a 404 landing page in case when someone tries to access an endpoint that does not exist.

## Tools
Adobe XD / Figma

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

### Motivation
An issue opened by a participant.

**Comment by sameersrivastava13** [comment]
@sarthakkundra below i have attached a 404 page that i have designed.

![Screenshot (40)](https://user-images.githubusercontent.com/56088741/90756613-39582200-e2fa-11ea-9cb1-898322f7d2b3.png)

**Comment by sameersrivastava13** [comment]
Please assign me this issue if the design is okay.
