### ISSUE TITLE
Create the Web UI Design

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#6]
## AIM

Create the Web UI Design in a widely-supported Design Software (Adobe XD/Figma).

## Details 

We are currently looking for three pages: 

- <b>Landing Page</b>: An attractive Landing Page which outlines the purpose of the Project and what it aims to achieve.
- <b>Input Form</b>: This form contains only one required input field, that takes an image of a Cell as input that is to be classified as Malarial Cell or not. [ Assigned to @bhanvimenghani ]
- <b>Result Page</b>: The Result is either presented as a Malarial Cell or not a Malarial Cell. 

## Contributors Guideline 

- One can work on one or more pages at a given time. Ask yourself to be assigned that Issue, so that you can make the PR.
- Submissions should be made in an apt form so that Web Developers can work on them seamlessly.
- The task is open to creativity. You can combine modern UI/UX philosophies to come up with your own design.

**Comment by AshutoshDash1999** [comment]
can i work on this issue?
@HarshCasper

**Comment by HarshCasper** [comment]
@AshutoshDash1999 You want to work on all the Pages or some specific pages?

**Comment by AshutoshDash1999** [comment]
@HarshCasper I want to create the landing page. Is there any deadline?

**Comment by HarshCasper** [comment]
@AshutoshDash1999 I have assigned you this Issue specifically for Landing Page. Deadline is for 7 Days.

**Comment by AshutoshDash1999** [comment]
@HarshCasper should I create my own design or wait for the designer?

**Comment by HarshCasper** [comment]
@AshutoshDash1999 You are not implementing the Code here. Read the Issue again. You have to use a Designing Software to make a design for Landing Page, not actually the code. You cannot wait for the designer since you are the one.

**Comment by AshutoshDash1999** [comment]
@HarshCasper I really apologize. I can't design. I want to contribute in fontend development. Can you please unassign me?

**Comment by ritiksoni00** [comment]
i can work on that but i will need the raw DESIGN of landing page

**Comment by ashishsahu1** [comment]
@HarshCasper can I work on this?

**Comment by HarshCasper** [comment]
@ritiksoni00 According to this, you have to create the Raw Design of Landing Page on a Designing Tool like Adobe XD/Figma 

@ashishsahu1 Will you be taking this up to create the designs in a Designing Software?

**Comment by bhanvimenghani** [comment]
@HarshCasper I can design using figma is this issue still open?

**Comment by HarshCasper** [comment]
@bhanvimenghani Can you specify which part you want to take up?

**Comment by bhanvimenghani** [comment]
Whichever is left unassigned

**Comment by HarshCasper** [comment]
@bhanvimenghani I have assigned you the Input Page. If you want, I can assign you for other pages as well

**Comment by bhanvimenghani** [comment]
@HarshCasper ya I will do those pages as well  so that the UI looks similar.

**Comment by ashishsahu1** [comment]
> @ritiksoni00 According to this, you have to create the Raw Design of Landing Page on a Designing Tool like Adobe XD/Figma
> 
> @ashishsahu1 Will you be taking this up to create the designs in a Designing Software?

Yes I will use Adobe XD

**Comment by HarshCasper** [comment]
@ashishsahu1 I have assigned you to make the Landing Page.

**Comment by bhanvimenghani** [comment]
@ashishsahu1 what color range will you be using in the landing page so that I can use the same range in the input page and result page

**Comment by ashishsahu1** [comment]
@bhanvimenghani  I am using these two colours and other colours that lies in between them.
**#3E0067
#22E9D5**
