### ISSUE TITLE
Implement a Script to create Train and Test Sets for our Dataset

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#7]
## AIM

Implement a Script to create Train and Test Sets for our Dataset

## Details

- Download the [Kaggle Dataset](https://www.kaggle.com/iarunava/cell-images-for-detecting-malaria)
- Load the Images from the Disk and scale them.
- Assign Binary Values to them and dump them to save Pre-Processing Time every time we load the Dataset.
- Split the Dataset into Training and Testing Sets.

**Comment by priyanka2109** [comment]
I would like to work on this.

**Comment by amoghatsunil** [comment]
I would like to work on this!!

**Comment by rohangawhade** [comment]
I would like to work on this.

**Comment by bolt25** [comment]
I would like to work on this

**Comment by erickeagle** [comment]
I would like to work o this

**Comment by HarshCasper** [comment]
I have assigned the Issue to you @priyanka2109 

You have 7 Days to make a PR on this Issue 🤗🙌

**Comment by ankit3699** [comment]
Can I start working on this issue in my branch?

**Comment by sahanabalappa** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
@ankit3699 and @sahanabalappa Issues are served on "First Come, First Serve" basis. If @priyanka2109 is not able to resolve this, other people in the thread would be assigned the Issue

**Comment by amandp13** [comment]
@HarshCasper I would like to work on this issue.

**Comment by sarthakkundra** [comment]
@amandp13 as commented by Harsh above the issues are assigned on FCFS basis. Although if the assigned person is unable to complete the work in 7 days you can request for it again. In the meantime be on the lookout for new issues or you can also create your own issue and we can approve them.

**Comment by amoghatsunil** [comment]
Yes..I am available
@BALaka-18
