### ISSUE TITLE
Create Routes in the React Application + Populate Mock Content

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#74]
## Type

New Feature

## Description

Create Routes in the React Application using React-Router and populate them with Mock Content for now.

## Tools

- React Router 
- JSX 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by Amber-Williams** [comment]
Looks like you don't have React installed on the repo yet or a package.json for your node modules . If I take this up, I will need to add React then have the app serve your template/*.html files using react router. This works for you?

**Comment by HarshCasper** [comment]
@Amber-Williams Actually this Project is being worked upon in Contributor's Hack 2020. We are having two parallel development lifecycle going on. One is with traditional HTML+CSS, Bootstrap and Flask while the other one is with React and Node. You can check out our parallel development branch [here](https://github.com/HakinCodes/Malaria-Detection/tree/react-tensorflowjs).

**Comment by Amber-Williams** [comment]
Cool I can pick this up
