### ISSUE TITLE
Create a Folder Structure for the React Frontend

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#76]
## Type

Advancement 

## Description

Create a Folder Structure for the React Frontend. Follow [this](https://dev.to/chrisachard/tips-for-organizing-react-projects-191) to get a good understanding of a good Folder Structure in a React Project.

## Tools

- None

(required tools/coding languages)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

### Motivation

To have a proper Folder Structure for all our Code and Components.

**Comment by sarthakkundra** [comment]
@mechiragjain You have 2 hours to address this comment or make a PR otherwise the issue will be assigned to someone else.

**Comment by Asim-2000** [comment]
I would like to have this issue resolved.

**Comment by BALaka-18** [comment]
> I would like to have this issue resolved.

@Asim-2000 you have 24 hours to complete this issue and create a PR.
Assigned.

**Comment by Asim-2000** [comment]
@BALaka-18 noted!
