### ISSUE TITLE
Create Mock Endpoints in the Flask Application

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#8]
## AIM 

Create Mock endpoints for our Flask Application.

## Details

We are currently looking for three pages: 

- <b>Landing Page</b>: An attractive Landing Page which outlines the purpose of the Project and what it aims to achieve. 
- <b>Input Form</b>: This form contains only one required input field, that takes an image of a Cell as input that is to be classified as Malarial Cell or not.
- <b>Result Page</b>: The Result is either presented as a Malarial Cell or not a Malarial Cell. 

You have to create mock endpoints which return a JSON Message on various routes.

**Comment by sameersrivastava13** [comment]
@HarshCasper I would like to work on this issue.

**Comment by erickeagle** [comment]
I would like to work on this issue.

**Comment by HarshCasper** [comment]
I have assigned you the Issue @sameersrivastava13 ✨

You can start working on the same 🤗
