### ISSUE TITLE
Remove a line from Malaria_detection.ipynb

### ISSUE THREAD

**Issue by bhadreshpsavani** [HakinCodes/Malaria-Detection#80]
## Type

Refactoring

## Description

[Malaria_detection.ipynb](https://github.com/HakinCodes/Malaria-Detection/blob/master/Notebooks/Malaria_detection.ipynb) in **Steps to solve the problem** section we have following steps, 
```
1. Loading the data.
2. Exploratory Data Analysis (EDA).
3. Data preprocessing.
4. Data augmentation.
5. Ploting images and its labels to understand how does an infected cell and uninfected cell looks like.
6. Spliting data in Train , Evaluation and Test set.
7. Creating a Convolution Neural Network function.
8. Wrapping it with Tensorflow Estimator function.
9. Training the data on Train data.
10. Evaluating on evaluation data.
11. Predicting on Test data
12. Ploting the predicted image and its respective True value and predicted value.
```
Step 5 which is `Ploting images and its labels to understand how does an infected cell and uninfected cell looks like.` should be removed since its EDA step and need to reorder the other steps after removal.

## Tools 

* Markdown

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Ya

### Motivation

To have better markdown for Notebook by writing more appropriate steps

**Comment by kahanikaar** [comment]
Is this issue still requires any additions, or can be closed for now? @bhadreshpsavani

**Comment by bhadreshpsavani** [comment]
Hi @kahanikaar we can close it,
@BALaka-18 can you please close this issue and add points in the leaderboard for the participant
