### ISSUE TITLE
Adding a favicon

### ISSUE THREAD

**Issue by sameersrivastava13** [HakinCodes/Malaria-Detection#83]
## Type

advancement in original

## Description

As we know favicon serves as branding for a website. Its main purpose is to help visitors locate your page easier when they have multiple tabs open. So i would like to add a favicon to our web application.

## Tools

HTML

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

yes

### Screenshot :

![Screenshot (63)](https://user-images.githubusercontent.com/56088741/90978246-12a02280-e56a-11ea-804d-2f377bd18443.png)

**Comment by sameersrivastava13** [comment]
@BALaka-18 thanks for assigning the issue.
Also please add the required labels.

**Comment by BALaka-18** [comment]
> @BALaka-18 thanks for assigning the issue.
> Also please add the required labels.

Done.
