### ISSUE TITLE
Build a Literature Survey for Transfer Learning + Popular Pre-Trained Models for Binary Classification

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#89]
## Type

Advancement 

## Description

Build a Literature Survey for Transfer Learning including some Popular Pre-Trained Models for Binary Classification. Add the following there: 

- What is Transfer Learning? 
- Use-Cases of Transfer Learning to solve Complex Problems 
- Popular Pre-Trained Models for Transfer Learning
- Comparative Case-Study of various Models

## Tools

- Markdown
- Python

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by ashishsahu1** [comment]
Should I work on this @HarshCasper

**Comment by kahanikaar** [comment]
Working as a mentor for the project in HakinCodes, can i make some additions here? @HarshCasper

**Comment by BALaka-18** [comment]
> Should I work on this @HarshCasper

@ashishsahu1 are yo working on any other issue currently ?

**Comment by ashishsahu1** [comment]
Not working on any of the issue, just landing page UI is yet to be reviewed @BALaka-18

**Comment by HarshCasper** [comment]
> Working as a mentor for the project in HakinCodes, can i make some additions here? @HarshCasper

Let's shift this conversation on Slack for better accessibility

**Comment by HarshCasper** [comment]
> Not working on any of the issue, just landing page UI is yet to be reviewed @BALaka-18

Assigned to you

**Comment by HarshCasper** [comment]
Are you working on this @ashishsahu1 ? 

It is way MUCH time now for this Issue.

**Comment by amoghatsunil** [comment]
I would like to work on this issue!

**Comment by rutujadhanawade** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
Assigned this to you @amoghatsunil

**Comment by v-sonawane** [comment]
I am willing to work on this issue.

**Comment by rutujadhanawade** [comment]
I want to work on this..

**Comment by HarshCasper** [comment]
I am assigning to you @v-sonawane

**Comment by v-sonawane** [comment]
Mentors do let me **know** if any changes required :-)

**Comment by v-sonawane** [comment]
Mentors could you review this PR please.
