### ISSUE TITLE
Create requirements.txt

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#9]
## AIM

Create a requirements text file for this project which will contain all the required libraries and frameworks for doing the data modelling.

**Comment by AdityaAshvin** [comment]
Can I work on this @HarshCasper ?

**Comment by sameersrivastava13** [comment]
@HarshCasper i would like to work on this issue.

**Comment by erickeagle** [comment]
i would like to work on this issue.

**Comment by HarshCasper** [comment]
I have assigned you the Issue @AdityaAshvin
