### ISSUE TITLE
Factory Application Pattern for the Flask App

### ISSUE THREAD

**Issue by kaustubhgupta** [HakinCodes/Malaria-Detection#95]
## Type

advancement 

## Description
The current flask application is just a single file with all the routes and configurations defined in a single file. It may happen in the future that this application increases in code and more routes added to the website which will make it difficult to maintain the code. Solution: Converting the current application into a factory application pattern which will make it easier to manage code.

## Tools
Python

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?
Yes

### Motivation
Easier maintainability of code in future, Participant of CH20

**Comment by kaustubhgupta** [comment]
I would like to work on this approach, can you assign this issue with appropriate labels to me?

**Comment by BALaka-18** [comment]
@HarshCasper @sarthakkundra @bhadreshpsavani @macabdul9 shall we assign him this issue ?

**Comment by BALaka-18** [comment]
@kaustubhgupta this is a basic setup that we've created, I don't think factory application pattern is needed as of now.
Closing it currently, will re-open when we need it, cool ?

**Comment by kaustubhgupta** [comment]
okay you can ping me if in future you want to shift to this pattern :-)

**Comment by BALaka-18** [comment]
> okay you can ping me if in future you want to shift to this pattern :-)

Yes sure @kaustubhgupta
