### ISSUE TITLE
Make a Navbar Component for the React Application

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#99]
## Type

Feature 

## Description

Create a Navbar component for the React Application. We will have three routes: 
- Home Page (`Landing Page`)
- About Page 
- Demo Page

The PR for adding routes has been made by @Amber-Williams so you can move forward and create a Navbar component using the same. Make sure to push your code on the `react-tensorflowjs` branch of the Project.

## Tools

- JSX
- CSS 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

**Comment by mechiragjain** [comment]
Okay will do that

**Comment by Shubham-1105** [comment]
I want to work on this

**Comment by BhawnaKochhar** [comment]
I want to work on this
